name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: sudo apt-get install tree cmake qtbase5-dev libxss-dev libxrandr-dev
    - name: Build
      run: |
        export CWD=`pwd`
        mkdir $CWD/build
        cd $CWD/build
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DSERVICE_GROUP=plugdev -DCMAKE_BUILD_TYPE=Release ..
        make -j2
        cpack -G DEB
