name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: sudo apt-get install tree cmake qtbase5-dev libxss-dev libxrandr-dev
    - name: Build
      run: |
        export CWD=`pwd`
        mkdir $CWD/build-release-qt5
        cd $CWD/build-release-qt5
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
        make
        make DESTDIR=`pwd`/pkg install
        tree pkg
        mkdir $CWD/build-debug-qt5
        cd $CWD/build-debug-qt5
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make
