name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt update && sudo apt install cmake qtbase5-dev libxss-dev libxrandr-dev
    - name: Build and Package
      run: |
        mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DSERVICE_GROUP=plugdev -DCMAKE_BUILD_TYPE=Release ..
        make -j2
        cpack -G DEB
